os:
 - osx
language: node_js
sudo: false
node_js:
  - "8.9.0"
install:
  - npm install
script:
  - npm test
after_success: 
  - bash ./deploy.sh 
deploy:
  skip_cleanup: true 
  provider: gae
  keyfile: "gcloudkey.json"
  project: "service-link-website-206921"
  on:
    tags: true
    all_branches: true
    condition: "$TRAVIS_TAG =~ ^v(.+)"